### PR TITLE
Added past audit reports

### PR DESCRIPTION
**Pull request by rytimx**
Audit Report added under `audit/bridge/`

- [zkEVM Bridge Contract](https://github.com/trailofbits/publications/blob/master/reviews/2023-11-immutable-zkevmbridgecontracts-securityreview.pdf)
- [Flow rate contract](https://github.com/trailofbits/publications/blob/master/reviews/2023-08-immutable-securityreview.pdf)

### CODE REVIEW

**Comment by drinkcoffee** [comment]
I would rename: audits/bridge/flow-rate/202308-immutable-securityreview.pdf
to                         audits/bridge/flow-rate/202308-external-audit-trail-of-bits.pdf

**Comment by drinkcoffee** [comment]
I would rename: 
audits/bridge/zkevm/202311-immutable-zkevmbridgecontracts-securityreview.pdf
audits/bridge/zkevm/202311-external-audit-train-of-bits-zkevmbridgecontracts.pdf

**Comment by drinkcoffee** [comment]
That is,   YYYYNN-external-audit-<audit company>-name.pdf

**Comment by rytimx** [comment]
Thanks @drinkcoffee , rename the files as recommended.

**Comment by ermyas** [comment]
nit:
"..train-of-bits" -> "..tail-of-bits"

**Comment by ermyas** [comment]
should we be using the date on the final audit report instead?

**Comment by rytimx** [comment]
Thanks @ermyas , fixed the typo.

**Review by drinkcoffee — APPROVED** [review]

**Review by ermyas — APPROVED** [review]

**Pull request merged**
